### ISSUE TITLE
Making the time roll over past 24:00 into the new day does not work

### ISSUE THREAD

**Issue by GriekseSalade** [Th3Shadowbroker/OuroborosMines#76]
Using the time 22:00-01:00 seems to not work
```
inherit: false
materials:
  iron_ore:
    replacements:
    - stone
    cooldown: 4500
    rich-chance: 3
    rich-amount: 5-6
  emerald_ore:
    replacements:
    - stone
    cooldown: 7200-9000
    rich-chance: 3
    rich-amount: 2-3
  diamond_ore:
    replacements:
    - stone
    cooldown: 7200-9000
    rich-chance: 3
    rich-amount: 2-3
    
openingHours:
  enabled: true
  realtime: 
      - 22:00-01:00
  announcements:
    opening: true
    closing: true
    worlds:
    - world
```

chat:
  messages:
    announcements:
      opening: "&2Mines 3,4 and 8 are now open!"
      closing: "&cMines 3,4 and 8 are now closed. Come back tomorrow!"
    minesClosed: "&cThis mine is closed come back later."

**Expected behavior**
As asked in a previous report one would expect the mines to remain op till 01:00

**Desktop (please complete the following information):**
 - Minecraft-version: 1.16.5
 - Server-version: Purpur 1.16.5 #1056

```
# OuroborosMines v1.10.0-SNAPSHOT by Th3Shadowbroker
# 
# When true all regions will be handled as OM-zone.
# Not recommended for big-servers as the replacement-tasks require a lot of scheduling.
default: false
chat:
  prefix: '&9[OM]'
  messages:
    awaitingRightClick: '&2Right-click the chest you want to create the drop group
      from or type &e/om dg&2 to cancel!'
    awaitingRightClickCancelled: '&cDrop group creation cancelled!'
    consoleNotAllowed: '&cThis command can not be executed from console!'
    dropGroupCreated: '&2Saved drop group &e%name%'
    dropGroupExists: '&cThere''s already a drop-group name &e%name%&c!'
    unrecognizedArgument: '&cUnrecognized argument'
    missingDropGroupName: '&cMissing drop-group name!'
    regionCustomize: '&2A new configuration file for &b%region%&2 has been created!'
    regionAlreadyCustomized: '&cThere''s already a configuration file for this region!'
    regionNotFound: '&cNo region found at your position!'
    reloadingConfig: '&2Reloading configuration...'
    reloadingRegionConfigurations: '&2Reloading region-configurations...'
    reloadedRegionConfigurations: '&2Loaded %count% region-specific configurations'
    reloadingDropGroups: '&2Reloading drop groups...'
    reloadedDropGroups: '&2Loaded %count% drop groups'
    worldNotFound: '&cWorld &e%world% &cnot found!'
    depositDiscovered: '&2You''ve discovered a %size% &e%material%&2 deposit!'
    depositSizes:
      small: small
      medium: medium
      large: large
    announcements:
      opening: '&2The mines are open!'
      closing: '&cThe mines are now closed. Come back tomorrow!'
    minesClosed: '&cThe mines are closed come back later.'
    error: '&cAn error occurred: %error%'
    help:
      customize: Generates a region-configuration.
      dropgroup: Generates a drop-group from a chest.
      reload: Reloads all configuration files.
materials:
  # coal_ore:
    # replacements:
    # - stone
    # cooldown: 20
  # gold_ore:
    # replacements:
    # - stone
    # cooldown: 30
  iron_ore:
    replacements:
    - stone
    cooldown: 3600
  emerald_ore:
    replacements:
    - stone
    cooldown: 7200-9000
    rich-chance: 3
    rich-amount: 2-3
  # redstone_ore:
    # replacements:
    # - stone
    # cooldown: 55
  diamond_ore:
    replacements:
    - stone
    cooldown: 7200-9000
    rich-chance: 3
    rich-amount: 2-3
  # lapis_ore:
    # replacements:
    # - stone
    # cooldown: 60
  # nether_gold_ore:
    # replacements:
    # - netherrack
    # cooldown: 50
  # nether_quartz_ore:
    # replacements:
    # - netherrack
    # cooldown: 50
  # ancient_debris:
    # replacements:
    # - netherrack
    # cooldown: 120
effects:
  deposit_discovered:
    sound: entity_player_levelup
experience:
  spawnOrbs: true
autoPickup: true
openingHours:
  enabled: false
  realtime: 
    - 00:00-06:00
    - 18:00-23:59
  announcements:
    opening: false
    closing: false
    worlds:
    - world
timezone: Europe/Berlin
placeholders:
  openingHours:
    format: '%h%:%m%:%s%'
    open: Now!

```
