### ISSUE TITLE
[EcoSkills] Eco Effect not activating after setting OM mine region flag too 'true'

### ISSUE THREAD

**Issue by ryxan** [Th3Shadowbroker/OuroborosMines#92]
**Describe the bug**

**To Reproduce**

setup a mine with gold, coal, or oak wood.
mine without the flag for the mine set to true.
the effect will activate fine, the player with say, hi.
but as soon as the mine region flag is set too true, the effect activation does not happen.

im not sure if its with other Eco plugins, but its not working with Actions.
not sure if this is OM or Eco.

**Expected behavior**

**Desktop (please complete the following information):**
 - Minecraft-version: 1.19.4
 - Server-version: 1.19.4  version 491 items adder is not running past that so I haven't updated.

thats the region config.
```
inherit: false
materials:
  itemsadder:gemrocks_block:
    replacements:
    - cobblestone
    cooldown: 10
  coal_ore:
    replacements:
    - stone
    cooldown: 20
  gold_ore:
    replacements:
    - stone
    cooldown: 30
  iron_ore:
    replacements:
    - stone
    cooldown: 40
  emerald_ore:
    replacements:
    - stone
    cooldown: 50
  oak_wood:
    replacements:
    - air
    cooldown: 1
  diamond_ore:
    replacements:
    - stone
    cooldown: 120
```

thats the actins config

```
enabled: true
effects:
  - id: run_player_command
    args:
      chance: 100
      command: "say hi"
    triggers:
      - mine_block
    filters:
      blocks:
        - gold_ore
        - coal_ore
        - oak_wood

conditions: [ ]
```
