### ISSUE TITLE
Farm not working

### ISSUE THREAD

**Issue by titidelaff** [Th3Shadowbroker/OuroborosMines#94]
Wheat, carrot and potato not working

**To Reproduce**
create wg region farm, om /customize, set material:

```yaml
wheat:
  replacements:
  - air
  cooldown: 10
  properties:
    age: 7
    resetAge: true 
```

**Expected behavior**
Wheat replace by air and replace 10s after by new wheat

 - Server-version: Paper 1.20

**Comment by Th3Shadowbroker** [comment]
Hi @titidelaff ,
may I ask what version of OM you are using?

**Comment by titidelaff** [comment]
1.13.0-SNAPSHOT

**Comment by Th3Shadowbroker** [comment]
Alright 👍🏻
I'll try to replicate it.

**Comment by Th3Shadowbroker** [comment]
I cannot replicate the described behaviour. The following configuration works for me with 1.13.0-SNAPSHOT:

farm.yml
```yaml
inherit: false
materials:
  wheat:
      replacements:
      - air
      cooldown: 10
      properties:
        age: 7
        resetAge: true 
  carrots:
      replacements:
      - air
      cooldown: 10
      properties:
        age: 7
        resetAge: true 
  potatoes:
      replacements:
      - air
      cooldown: 10
      properties:
        age: 7
        resetAge: true 
```

This is the expected behaviour:
https://github.com/Th3Shadowbroker/OuroborosMines/assets/8280615/e6b11168-ed15-448a-b321-1eb394b78754

What is displayed when you type `/rg info`?
